type Colors = {
  black: string;
  white: string;
  eerieBlack: string;
  eerieBlackSecondary: string;
  davysGrey: string;
  outerSpace: string;
  coralRed: string;
  platinum: string;
  quickSilver: string;
  lotion: string;
  darkCharcoal: string;
  darkCharcoal10Alpha: string;
  darkCharcoal30Alpha: string;
  coolGrey: string;
  metallicRed: string;
  ultraMarineBlue: string;
  lightSilver: string;
  gray: string;
  silverSand: string;
  oldLace: string;
  oldLace30Alpha: string;
  platinumSecondary: string;
  philippineGray: string;
  ruddyBrown: string;
  castletonGreen: string;
  americanGreen: string;
  spacecadet: string;
  whiteChoclate: string;
  lavender: string;
  jordyBlue: string;
  forestGreen: string;
  deepSaffron: string;
  japaneseIndigo: string;
  oxfordBlue: string;
  spacecadetSecondary: string;
  gainsBoro: string;
  gainsBoroSecondary: string;
  madderLake: string;
  northTexasGreen: string;
  melon: string;
  graniteGray: string;
  madderLake06Alpha: string;
  cadetGray: string;
  semiTransparentWhite: string;
  gradientBackground: string;
  gradientBackgroundSecondary: string;
  gradientBackgroundTertiary: string;
  gradientBackgroundQuaternary: string;
  black90Alpha: string;
  transparentBlack: string;
  black91Alpha: string;
  darkCharcoal70Alpha: string;
  black30Alpha: string;
  black60Alpha: string;
  slateGray: string;
  translucentWhite: string;
  black20Opacity: string;
  northTexasGreenSecondary: string;
  jordyBlueSecondary: string;
  spanishGray: string;
  black0Opacity: string;
  whisperGray: string;
  whiteSmoke: string;
  charcoalGray: string;
  transparentCharcoalGray: string;
  submarine: string;
  whiteEcho: string;
  hydroCarbon: string;
};

export const colors: Colors = {
  black: '#000',
  white: '#FFF',
  eerieBlack: '#17171A',
  eerieBlackSecondary: '#1A1C1E',
  davysGrey: '#555559',
  outerSpace: '#45474D',
  coralRed: '#FF3640',
  platinum: '#E1E1E2',
  quickSilver: '#A7A7A8',
  lotion: '#FAFAFA',
  darkCharcoal: '#2C2E33',
  darkCharcoal10Alpha: '#2C2E331A',
  coolGrey: '#8C93A2',
  metallicRed: '#A42A30',
  ultraMarineBlue: '#3355FF',
  lightSilver: '#D9D9D9',
  gray: '#7E7E81',
  silverSand: '#B8BECC',
  madderLake: '#D33038',
  oldLace: '#FCF5E6',
  platinumSecondary: '#E6E0E0',
  philippineGray: '#998F8A',
  ruddyBrown: '#C95D2E',
  castletonGreen: '#005A3B',
  americanGreen: '#24B354',
  spacecadet: '#1C275E',
  spacecadetSecondary: '#111C57',
  whiteChoclate: '#F2E2DA',
  lavender: '#E6E6FF',
  jordyBlue: '#98A9FF',
  forestGreen: '#118120',
  deepSaffron: '#FF9633',
  japaneseIndigo: '#2E3D4D',
  oxfordBlue: '#08253F',
  gainsBoro: '#DCDFE6',
  gainsBoroSecondary: '#DCDCDC',
  madderLake06Alpha: '#D330380F',
  melon: '#FFABAF',
  northTexasGreen: '#059033',
  graniteGray: '#606060',
  cadetGray: '#8C93A214',
  darkCharcoal30Alpha: '#2C2E334D',
  oldLace30Alpha: '#FCF5E64D',
  semiTransparentWhite: '#FFFFFFF2',
  gradientBackground: '#F5F5F5',
  gradientBackgroundSecondary: '#EBEBEB',
  gradientBackgroundTertiary: '#E1E1E1',
  gradientBackgroundQuaternary: '#D7D7D7',
  black90Alpha: '#000000E6',
  transparentBlack: '#00000000',
  black91Alpha: '#0000009d',
  darkCharcoal70Alpha: '#2C2E33B3',
  black30Alpha: '#0000004D',
  black60Alpha: '#00000099',
  slateGray: '#AFB3C5',
  translucentWhite: '#FFFFFFCC',
  black20Opacity: 'rgba(0, 0, 0, 0.2)',
  northTexasGreenSecondary: '#089A39',
  jordyBlueSecondary: '#8C9FFF',
  spanishGray: '#7474744d',
  black0Opacity: 'rgba(0, 0, 0, 0)',
  whisperGray: 'rgba(244, 244, 244, 1)',
  whiteSmoke: 'rgba(244, 244, 244, 1)',
  transparentCharcoalGray: 'rgba(69, 71, 77, 1)',
  charcoalGray: 'rgba(69, 71, 77, 1)',
  submarine: '#B7CCCB',
  whiteEcho: '#E9E9E9',
  hydroCarbon: '#4b5563'
};
