import { colors } from '@src/themes/colors';

export type AppTheme = {
  bodyTextMain: string;
  bodyTextSecondary: string;
  bodyTextOther: string;
  bodyTextDarkTheme: string;
  bodyTextHyperlinked: string;
  carouselTextMain: string;
  carouselTextSecondary: string;
  carouselTextOther: string;
  carouselTextDarkTheme: string;
  carouselTextDescription: string;
  sectionTextTitleSpecial: string;
  sectionTextSubtitleSpecial: string;
  sectionTextTitleNormal: string;
  sectionTextDarkThemePages: string;
  sectionTextOther: string;
  titleForegroundInteractiveDefault: string;
  titleForegroundInteractiveHover: string;
  titleForegroundInteractivePressed: string;
  inputOutlineInteractiveDefault: string;
  inputOutlineInteractiveHover: string;
  inputOutlineInteractivePressed: string;
  inputFillforegroundInteractiveDefault: string;
  inputFillForegroundInteractiveFocused: string;
  inputFillForegroundInteractiveFilled: string;
  inputFillForegroundInteractiveError: string;
  inputFillForegroundInteractiveError06Alpha: string;
  inverse: string;
  dividerBlack: string;
  dividerPrimary: string;
  dividerSecondary: string;
  dividerGrey: string;
  mainBackgroundDefault: string;
  mainBackgroundSecondary: string;
  mainBackgrunforproductionPage: string;
  mainBackgroundforIcons: string;
  tabsBackgroundSelceted: string;
  tabsBackgroundDefault: string;
  tabsBackgroundOutline: string;
  specificSectionBackgroundMood1: string;
  specificSectionBackgroundMood2: string;
  specificSectionBackgroundMood3: string;
  specificSectionBackgroundMood4: string;
  specificSectionBackgroundSurface: string;
  specificSectionBackgroundSurface1: string;
  specificSectionBackgroundSurface2: string;
  specificSectionBackgroundSurface3: string;
  specificSectionBackgroundSurface4: string;
  specificSectionBackgroundSurface5: string;
  specificSectionBackgroundSurface6: string;
  systemSuccess: string;
  systemError: string;
  systemAlert: string;
  forDarkLayerSliderSelected: string;
  forDarkLayerSliderDefault: string;
  forLightThemeSliderSelected: string;
  forLightThemeSliderDefault: string;
  newsTextTitlePrincipal: string;
  newsTextPictureCarouselTitle: string;
  newsTextHorizontalVideoTitle: string;
  newsTextDarkThemePages: string;
  menusTextHeaderActive: string;
  menusTextHeaderInactive: string;
  menusTextDarkThemePagesActive: string;
  chipTextActive: string;
  chipTextInactive: string;
  interestButtonActive: string;
  chipTextDarkThemePagesActive: string;
  liveBlogTextTitle: string;
  liveBlogTextBulletsBodyDescription: string;
  liveBlogTextDarkThemePagesTitle: string;
  liveBlogTextDarkThemesPagesDescription: string;
  liveBlogEnteriesIndicator: string;
  liveTextSummary: string;
  subtitleTextSubtitle: string;
  tagsTextBreakingNews: string;
  tagsTextCategory: string;
  tagsTextLive: string;
  tagsTextAuthor: string;
  tagsTextBlackThemeTags: string;
  labelsTextLabelPlace: string;
  labelsTextLabelPlay: string;
  labelsTextLabelTime: string;
  labelsTextLabelName: string;
  labelsTextLabelDarkTheme: string;
  onBoardingTextLabel: string;
  onBoardingTextPlaceholder: string;
  onBoardingTextInputText: string;
  onBoardingTextErrorHelperText: string;
  toastAndAlertsTextSuccess: string;
  toastAndAlertsTextInfo: string;
  toastAndAlertsTextWarning: string;
  toastAndAlertsTextError: string;
  toastAndAlertsTextBackground: string;
  toastAndAlertsTextLiveToast: string;
  primaryCTATextDefault: string;
  primaryCTATextHover: string;
  primaryCTATextPressed: string;
  primaryCTATextDisabled: string;
  primaryCTATextSecondaryText: string;
  primaryCTATextGreyPrimaryText: string;
  actionCTATextDefault: string;
  actionCTATextHover: string;
  actionCTATextPressed: string;
  actionCTATextDisabled: string;
  actionCTATextSecondary: string;
  actionCTATextForDarkTheme: string;
  actionCTATextForDarkThemeHover: string;
  actionCTATextForDarkThemePressed: string;
  blockQuotesTextQuote: string;
  blockQuotesTextText: string;
  filledButtonPrimary: string;
  filledButtonSecondary: string;
  filledButtonAction: string;
  filledButtonDisabled: string;
  filledButtonHover: string;
  filledButtonPressed: string;
  outlinedButtonPrimaryOutline: string;
  outlinedButtonSecondaryOutline: string;
  outlinedButtonAction: string;
  outlinedButtonDisabled: string;
  outlinedButtonOutline: string;
  outlinedButtonHover: string;
  outlinedButtonPressed: string;
  outlinedButtonDarkTheme: string;
  greyButtonPrimary: string;
  greyButtonSecondaryOutline: string;
  greyButtonHover: string;
  greyButtonPressed: string;
  greyButtonDisabled: string;
  iconIconographyPrimary: string;
  iconIconographyActiveState: string;
  iconIconographyGenericState: string;
  iconIconographyDisabledState1: string;
  iconIconographyDisabledState2: string;
  iconIconographyDisabledState3: string;
  iconIconographyVerifiedState: string;
  iconIconographyOtherState: string;
  iconIconographyIconBoundaries: string;
  iconIconographyInfoIcons: string;
  iconIconographyWarningIcons: string;
  iconIconographyError: string;
  iconIconographyHover: string;
  iconIconographyPressed: string;
  toggleIcongraphyPrimary: string;
  toggleIcongraphySwitch: string;
  toggleIcongraphyDisabledState: string;
  checkBoxIcongraphyActiveState: string;
  checkBoxIcongraphyDefaultState: string;
  checkBoxIcongraphyDisableState: string;
  radioButtonIcongraphyActiveState: string;
  radioButtonIcongraphyDisableState: string;
  borderWidth: string;
  trackDisabled: string;
  errorTextColor: string;
  borderColor: string;
  skeletonLoaderBackground: string;
  overlayGray: string;
  statusBarTheme: string;
  titleForegroundInteractiveDefault30Alpha: string;
  semiTransparentWhite: string;
  gradientBackground: string;
  gradientBackgroundSecondary: string;
  gradientBackgroundTertiary: string;
  gradientBackgroundQuaternary: string;
  gradientOverlayDark: string;
  gradientTransparentBlack: string;
  gradientOverlay91Alpha: string;
  captionsBackground: string;
  gradientBlack30Alpha: string;
  overlayWhite: string;
  brandColorSecondaryLogo: string;
  colorSecondary200: string;
  colorSecondary600: string;
  buttonOutlineGrey: string;
  backgroundTabOutline: string;
  foregroundInteractiveTitularDefault: string;
  loaderBackground: string;
  interestButtonBackground: string;
  gradientBlack20Alpha: string;
  neutralBackground: string;
  actionCTAToastDefault: string;
  actionCTAToastError: string;
  gradientSilver30Alpha: string;
  gradientBlack0Alpha: string;
  reelBackground: string;
  nPlusFocusModalBackground: string;
  adaptiveText: string;
  bottomTabColor1: string;
  bottomTabColor2: string;
  textHeadingChipInactive: string;
  submarineGreen: string;
  neutralDivider: string;
  widgetBackground: string;
  dividerAdaptive: string;
  adsBackground: string;
  chipBackground: string;
  buttonFilledSecondaryOutline: string;
  highlightTextPrimary: string;
  adaptiveDangerSecondary: string;
  textAccentSecondary: string;
  ctaAccentAdaptive: string;
  modalBackground: string;
  accentSecondaryPressed: string;
};

export const lightTheme: AppTheme = {
  bodyTextMain: colors.davysGrey,
  bodyTextSecondary: colors.gray,
  bodyTextOther: colors.darkCharcoal,
  bodyTextDarkTheme: colors.white,
  bodyTextHyperlinked: colors.ultraMarineBlue,
  carouselTextMain: colors.davysGrey,
  carouselTextSecondary: colors.gray,
  carouselTextOther: colors.darkCharcoal,
  carouselTextDescription: colors.silverSand,
  carouselTextDarkTheme: colors.white,
  sectionTextTitleSpecial: colors.darkCharcoal,
  sectionTextSubtitleSpecial: colors.darkCharcoal,
  sectionTextTitleNormal: colors.darkCharcoal,
  sectionTextDarkThemePages: colors.white,
  sectionTextOther: colors.oldLace,
  titleForegroundInteractiveDefault: colors.darkCharcoal,
  titleForegroundInteractiveHover: colors.davysGrey,
  titleForegroundInteractivePressed: colors.gray,
  inputOutlineInteractiveDefault: colors.white,
  inputOutlineInteractiveHover: colors.white,
  inputOutlineInteractivePressed: colors.white,
  inputFillforegroundInteractiveDefault: colors.platinum,
  inputFillForegroundInteractiveFocused: colors.gray,
  inputFillForegroundInteractiveFilled: colors.quickSilver,
  inputFillForegroundInteractiveError: colors.madderLake,
  inputFillForegroundInteractiveError06Alpha: colors.madderLake06Alpha,
  inverse: colors.oldLace,
  dividerBlack: colors.darkCharcoal,
  dividerPrimary: colors.coolGrey,
  dividerSecondary: colors.white,
  dividerGrey: colors.gainsBoro,
  mainBackgroundDefault: colors.lotion,
  mainBackgroundSecondary: colors.white,
  mainBackgrunforproductionPage: colors.darkCharcoal,
  mainBackgroundforIcons: colors.gainsBoro,
  tabsBackgroundSelceted: colors.outerSpace,
  tabsBackgroundDefault: colors.white,
  tabsBackgroundOutline: colors.silverSand,
  specificSectionBackgroundMood1: colors.ruddyBrown,
  specificSectionBackgroundMood2: colors.castletonGreen,
  specificSectionBackgroundMood3: colors.americanGreen,
  specificSectionBackgroundMood4: colors.ultraMarineBlue,
  specificSectionBackgroundSurface: colors.darkCharcoal,
  specificSectionBackgroundSurface1: colors.spacecadet,
  specificSectionBackgroundSurface2: colors.eerieBlack,
  specificSectionBackgroundSurface3: colors.japaneseIndigo,
  specificSectionBackgroundSurface4: colors.silverSand,
  specificSectionBackgroundSurface5: colors.lavender,
  specificSectionBackgroundSurface6: colors.jordyBlue,
  systemSuccess: colors.forestGreen,
  systemError: colors.madderLake,
  systemAlert: colors.deepSaffron,
  forDarkLayerSliderSelected: colors.white,
  forDarkLayerSliderDefault: colors.white,
  forLightThemeSliderSelected: colors.quickSilver,
  forLightThemeSliderDefault: colors.quickSilver,
  newsTextTitlePrincipal: colors.darkCharcoal,
  newsTextPictureCarouselTitle: colors.outerSpace,
  newsTextHorizontalVideoTitle: colors.darkCharcoal,
  newsTextDarkThemePages: colors.white,
  menusTextHeaderActive: colors.darkCharcoal,
  menusTextHeaderInactive: colors.gray,
  menusTextDarkThemePagesActive: colors.white,
  chipTextActive: colors.darkCharcoal,
  chipTextInactive: colors.coolGrey,
  interestButtonActive: colors.darkCharcoal,
  chipTextDarkThemePagesActive: colors.white,
  liveBlogTextTitle: colors.darkCharcoal,
  liveBlogTextBulletsBodyDescription: colors.darkCharcoal,
  liveBlogTextDarkThemePagesTitle: colors.white,
  liveBlogTextDarkThemesPagesDescription: colors.white,
  liveBlogEnteriesIndicator: colors.slateGray,
  liveTextSummary: colors.darkCharcoal,
  subtitleTextSubtitle: colors.outerSpace,
  tagsTextBreakingNews: colors.coralRed,
  tagsTextCategory: colors.coralRed,
  tagsTextLive: colors.coralRed,
  tagsTextAuthor: colors.darkCharcoal,
  tagsTextBlackThemeTags: colors.white,
  labelsTextLabelPlay: colors.darkCharcoal,
  labelsTextLabelTime: colors.coolGrey,
  labelsTextLabelName: colors.coolGrey,
  labelsTextLabelDarkTheme: colors.white,
  onBoardingTextLabel: colors.outerSpace,
  onBoardingTextPlaceholder: colors.coolGrey,
  onBoardingTextInputText: colors.darkCharcoal,
  onBoardingTextErrorHelperText: colors.madderLake,
  toastAndAlertsTextSuccess: colors.northTexasGreen,
  toastAndAlertsTextInfo: colors.ultraMarineBlue,
  toastAndAlertsTextWarning: colors.deepSaffron,
  toastAndAlertsTextError: colors.madderLake,
  toastAndAlertsTextBackground: colors.white,
  toastAndAlertsTextLiveToast: colors.coralRed,
  primaryCTATextDefault: colors.white,
  primaryCTATextHover: colors.outerSpace,
  primaryCTATextPressed: colors.white,
  primaryCTATextDisabled: colors.quickSilver,
  primaryCTATextSecondaryText: colors.coralRed,
  primaryCTATextGreyPrimaryText: colors.outerSpace,
  actionCTATextDefault: colors.darkCharcoal,
  actionCTATextHover: colors.melon,
  actionCTATextPressed: colors.madderLake,
  actionCTATextDisabled: colors.quickSilver,
  actionCTATextSecondary: colors.coralRed,
  actionCTATextForDarkTheme: colors.white,
  actionCTATextForDarkThemeHover: colors.melon,
  actionCTATextForDarkThemePressed: colors.coralRed,
  blockQuotesTextQuote: colors.gray,
  blockQuotesTextText: colors.davysGrey,
  filledButtonPrimary: colors.coralRed,
  filledButtonSecondary: colors.white,
  filledButtonAction: colors.eerieBlack,
  filledButtonDisabled: colors.quickSilver,
  filledButtonHover: colors.melon,
  filledButtonPressed: colors.madderLake,
  outlinedButtonPrimaryOutline: colors.coralRed,
  outlinedButtonSecondaryOutline: colors.platinum,
  outlinedButtonAction: colors.eerieBlack,
  outlinedButtonDisabled: colors.quickSilver,
  outlinedButtonOutline: colors.white,
  outlinedButtonHover: colors.melon,
  outlinedButtonPressed: colors.madderLake,
  outlinedButtonDarkTheme: colors.outerSpace,
  greyButtonPrimary: colors.outerSpace,
  greyButtonSecondaryOutline: colors.outerSpace,
  greyButtonHover: colors.gray,
  greyButtonPressed: colors.platinum,
  greyButtonDisabled: colors.platinum,
  iconIconographyPrimary: colors.coralRed,
  iconIconographyActiveState: colors.white,
  iconIconographyGenericState: colors.darkCharcoal,
  iconIconographyDisabledState1: colors.quickSilver,
  iconIconographyDisabledState2: colors.outerSpace,
  iconIconographyDisabledState3: colors.gray,
  iconIconographyVerifiedState: colors.northTexasGreen,
  iconIconographyOtherState: colors.japaneseIndigo,
  iconIconographyIconBoundaries: colors.platinum,
  iconIconographyInfoIcons: colors.ultraMarineBlue,
  iconIconographyWarningIcons: colors.deepSaffron,
  iconIconographyError: colors.madderLake,
  iconIconographyHover: colors.melon,
  iconIconographyPressed: colors.madderLake,
  toggleIcongraphyPrimary: colors.coralRed,
  toggleIcongraphySwitch: colors.white,
  toggleIcongraphyDisabledState: colors.platinum,
  checkBoxIcongraphyActiveState: colors.darkCharcoal,
  checkBoxIcongraphyDefaultState: colors.darkCharcoal,
  checkBoxIcongraphyDisableState: colors.darkCharcoal,
  radioButtonIcongraphyActiveState: colors.coralRed,
  radioButtonIcongraphyDisableState: colors.darkCharcoal,
  statusBarTheme: colors.white,
  titleForegroundInteractiveDefault30Alpha: colors.darkCharcoal30Alpha,
  labelsTextLabelPlace: colors.coolGrey,
  semiTransparentWhite: colors.semiTransparentWhite,
  gradientBackground: colors.gradientBackground,
  gradientBackgroundSecondary: colors.gradientBackgroundSecondary,
  gradientBackgroundTertiary: colors.gradientBackgroundTertiary,
  gradientBackgroundQuaternary: colors.gradientBackgroundQuaternary,
  gradientOverlayDark: colors.black90Alpha,
  gradientTransparentBlack: colors.transparentBlack,
  gradientOverlay91Alpha: colors.black91Alpha,
  captionsBackground: colors.darkCharcoal70Alpha,
  gradientBlack30Alpha: colors.black30Alpha,
  overlayWhite: colors.translucentWhite,
  buttonOutlineGrey: colors.graniteGray,
  backgroundTabOutline: colors.silverSand,
  loaderBackground: colors.black,
  interestButtonBackground: colors.coolGrey,
  gradientBlack20Alpha: colors.black20Opacity,
  neutralBackground: colors.platinumSecondary,
  gradientSilver30Alpha: colors.spanishGray,
  gradientBlack0Alpha: colors.black0Opacity,
  submarineGreen: colors.submarine,
  neutralDivider: colors.gainsBoro,

  //TODO:need to discuss with UI/UX team
  borderWidth: colors.darkCharcoal10Alpha,
  trackDisabled: colors.lightSilver,
  errorTextColor: colors.metallicRed,
  borderColor: colors.quickSilver,
  skeletonLoaderBackground: colors.platinum,
  overlayGray: colors.cadetGray,
  brandColorSecondaryLogo: colors.white,
  colorSecondary200: colors.quickSilver,
  colorSecondary600: colors.darkCharcoal,
  foregroundInteractiveTitularDefault: colors.darkCharcoal,
  actionCTAToastDefault: colors.northTexasGreenSecondary,
  actionCTAToastError: colors.madderLake,
  reelBackground: colors.black,
  nPlusFocusModalBackground: colors.oldLace30Alpha,
  adaptiveText: colors.black,
  bottomTabColor1: colors.whisperGray,
  bottomTabColor2: colors.whiteSmoke,
  textHeadingChipInactive: colors.coolGrey,
  widgetBackground: colors.white,
  dividerAdaptive: colors.coolGrey,
  adsBackground: colors.whiteEcho,
  chipBackground: colors.hydroCarbon,
  buttonFilledSecondaryOutline: colors.melon,
  highlightTextPrimary: colors.white,
  adaptiveDangerSecondary: colors.gray,
  textAccentSecondary: colors.jordyBlueSecondary,
  ctaAccentAdaptive: colors.coralRed,
  modalBackground: colors.black60Alpha,
  accentSecondaryPressed: colors.madderLake
};

export const darkTheme: AppTheme = {
  bodyTextMain: colors.white,
  bodyTextSecondary: colors.lotion,
  bodyTextOther: colors.platinum,
  bodyTextDarkTheme: colors.white,
  bodyTextHyperlinked: colors.jordyBlueSecondary,
  carouselTextMain: colors.platinum,
  carouselTextSecondary: colors.platinum,
  carouselTextOther: colors.white,
  carouselTextDescription: colors.silverSand,
  carouselTextDarkTheme: colors.white,
  sectionTextTitleSpecial: colors.white,
  sectionTextSubtitleSpecial: colors.white,
  sectionTextTitleNormal: colors.white,
  sectionTextDarkThemePages: colors.white,
  sectionTextOther: colors.oldLace,
  titleForegroundInteractiveDefault: colors.oldLace,
  titleForegroundInteractiveHover: colors.platinumSecondary,
  titleForegroundInteractivePressed: colors.philippineGray,
  inputOutlineInteractiveDefault: colors.outerSpace,
  inputOutlineInteractiveHover: colors.outerSpace,
  inputOutlineInteractivePressed: colors.outerSpace,
  inputFillforegroundInteractiveDefault: colors.davysGrey,
  inputFillForegroundInteractiveFocused: colors.white,
  inputFillForegroundInteractiveFilled: colors.platinum,
  inputFillForegroundInteractiveError: colors.madderLake,
  inputFillForegroundInteractiveError06Alpha: colors.madderLake06Alpha,
  inverse: colors.darkCharcoal,
  dividerBlack: colors.lotion,
  dividerPrimary: colors.coolGrey,
  dividerSecondary: colors.white,
  dividerGrey: colors.gray,
  mainBackgroundDefault: colors.darkCharcoal,
  mainBackgroundSecondary: colors.outerSpace,
  mainBackgrunforproductionPage: colors.darkCharcoal,
  mainBackgroundforIcons: colors.outerSpace,
  tabsBackgroundSelceted: colors.lotion,
  tabsBackgroundDefault: colors.outerSpace,
  tabsBackgroundOutline: colors.outerSpace,
  specificSectionBackgroundMood1: colors.ruddyBrown,
  specificSectionBackgroundMood2: colors.castletonGreen,
  specificSectionBackgroundMood3: colors.americanGreen,
  specificSectionBackgroundMood4: colors.ultraMarineBlue,
  specificSectionBackgroundSurface: colors.japaneseIndigo,
  specificSectionBackgroundSurface1: colors.spacecadet,
  specificSectionBackgroundSurface2: colors.eerieBlack,
  specificSectionBackgroundSurface3: colors.white,
  specificSectionBackgroundSurface4: colors.davysGrey,
  specificSectionBackgroundSurface5: colors.spacecadetSecondary,
  specificSectionBackgroundSurface6: colors.jordyBlue,
  systemSuccess: colors.forestGreen,
  systemError: colors.madderLake,
  systemAlert: colors.deepSaffron,
  forDarkLayerSliderSelected: colors.white,
  forDarkLayerSliderDefault: colors.white,
  forLightThemeSliderSelected: colors.white,
  forLightThemeSliderDefault: colors.white,
  newsTextTitlePrincipal: colors.lotion,
  newsTextPictureCarouselTitle: colors.platinum,
  newsTextHorizontalVideoTitle: colors.lotion,
  newsTextDarkThemePages: colors.white,
  menusTextHeaderActive: colors.platinum,
  menusTextHeaderInactive: colors.gray,
  menusTextDarkThemePagesActive: colors.white,
  chipTextActive: colors.platinum,
  chipTextInactive: colors.silverSand,
  interestButtonActive: colors.white,
  chipTextDarkThemePagesActive: colors.white,
  liveBlogTextTitle: colors.lotion,
  liveBlogTextBulletsBodyDescription: colors.platinum,
  liveBlogTextDarkThemePagesTitle: colors.white,
  liveBlogTextDarkThemesPagesDescription: colors.white,
  liveBlogEnteriesIndicator: colors.slateGray,
  liveTextSummary: colors.lotion,
  subtitleTextSubtitle: colors.platinum,
  tagsTextBreakingNews: colors.white,
  tagsTextCategory: colors.white,
  tagsTextLive: colors.white,
  tagsTextAuthor: colors.white,
  tagsTextBlackThemeTags: colors.white,
  labelsTextLabelPlace: colors.coolGrey,
  labelsTextLabelPlay: colors.white,
  labelsTextLabelTime: colors.coolGrey,
  labelsTextLabelName: colors.coolGrey,
  labelsTextLabelDarkTheme: colors.white,
  onBoardingTextLabel: colors.lotion,
  onBoardingTextPlaceholder: colors.coolGrey,
  onBoardingTextInputText: colors.white,
  onBoardingTextErrorHelperText: colors.madderLake,
  toastAndAlertsTextSuccess: colors.northTexasGreen,
  toastAndAlertsTextInfo: colors.ultraMarineBlue,
  toastAndAlertsTextWarning: colors.deepSaffron,
  toastAndAlertsTextError: colors.madderLake,
  toastAndAlertsTextBackground: colors.darkCharcoal,
  toastAndAlertsTextLiveToast: colors.coralRed,
  primaryCTATextDefault: colors.white,
  primaryCTATextHover: colors.outerSpace,
  primaryCTATextPressed: colors.white,
  primaryCTATextDisabled: colors.gray,
  primaryCTATextSecondaryText: colors.coralRed,
  primaryCTATextGreyPrimaryText: colors.white,
  actionCTATextDefault: colors.white,
  actionCTATextHover: colors.melon,
  actionCTATextPressed: colors.madderLake,
  actionCTATextDisabled: colors.gray,
  actionCTATextSecondary: colors.coralRed,
  actionCTATextForDarkTheme: colors.white,
  actionCTATextForDarkThemeHover: colors.melon,
  actionCTATextForDarkThemePressed: colors.coralRed,
  interestButtonBackground: colors.white,
  blockQuotesTextQuote: colors.coolGrey,
  blockQuotesTextText: colors.quickSilver,
  filledButtonPrimary: colors.coralRed,
  filledButtonSecondary: colors.white,
  filledButtonAction: colors.white,
  filledButtonDisabled: colors.outerSpace,
  filledButtonHover: colors.melon,
  filledButtonPressed: colors.madderLake,
  outlinedButtonPrimaryOutline: colors.coralRed,
  outlinedButtonSecondaryOutline: colors.gray,
  outlinedButtonAction: colors.white,
  outlinedButtonDisabled: colors.outerSpace,
  outlinedButtonOutline: colors.white,
  outlinedButtonHover: colors.melon,
  outlinedButtonPressed: colors.madderLake,
  outlinedButtonDarkTheme: colors.outerSpace,
  greyButtonPrimary: colors.white,
  greyButtonSecondaryOutline: colors.white,
  greyButtonHover: colors.quickSilver,
  greyButtonPressed: colors.lotion,
  greyButtonDisabled: colors.outerSpace,
  iconIconographyPrimary: colors.coralRed,
  iconIconographyActiveState: colors.white,
  iconIconographyGenericState: colors.white,
  iconIconographyDisabledState1: colors.quickSilver,
  iconIconographyDisabledState2: colors.lotion,
  iconIconographyDisabledState3: colors.gray,
  iconIconographyVerifiedState: colors.northTexasGreen,
  iconIconographyOtherState: colors.lotion,
  iconIconographyIconBoundaries: colors.platinum,
  iconIconographyInfoIcons: colors.ultraMarineBlue,
  iconIconographyWarningIcons: colors.deepSaffron,
  iconIconographyError: colors.madderLake,
  iconIconographyHover: colors.melon,
  iconIconographyPressed: colors.madderLake,
  toggleIcongraphyPrimary: colors.coralRed,
  toggleIcongraphySwitch: colors.white,
  toggleIcongraphyDisabledState: colors.platinum,
  checkBoxIcongraphyActiveState: colors.white,
  checkBoxIcongraphyDefaultState: colors.darkCharcoal,
  checkBoxIcongraphyDisableState: colors.white,
  radioButtonIcongraphyActiveState: colors.coralRed,
  radioButtonIcongraphyDisableState: colors.platinum,
  overlayGray: colors.cadetGray,
  statusBarTheme: colors.black,
  titleForegroundInteractiveDefault30Alpha: colors.oldLace30Alpha,
  semiTransparentWhite: colors.semiTransparentWhite,
  gradientBackground: colors.outerSpace,
  gradientBackgroundSecondary: colors.outerSpace,
  gradientBackgroundTertiary: colors.outerSpace,
  gradientBackgroundQuaternary: colors.outerSpace,
  gradientOverlayDark: colors.black90Alpha,
  gradientTransparentBlack: colors.transparentBlack,
  gradientOverlay91Alpha: colors.black91Alpha,
  captionsBackground: colors.darkCharcoal70Alpha,
  overlayWhite: colors.translucentWhite,
  gradientBlack30Alpha: colors.black30Alpha,
  buttonOutlineGrey: colors.graniteGray,
  backgroundTabOutline: colors.silverSand,
  loaderBackground: colors.black,
  gradientBlack20Alpha: colors.black20Opacity,
  neutralBackground: colors.davysGrey,
  gradientSilver30Alpha: colors.spanishGray,
  gradientBlack0Alpha: colors.black0Opacity,
  submarineGreen: colors.submarine,
  neutralDivider: colors.gainsBoro,
  //TODO:need to discuss with UI/UX team
  borderWidth: colors.darkCharcoal10Alpha,
  trackDisabled: colors.lightSilver,
  errorTextColor: colors.metallicRed,
  borderColor: colors.quickSilver,
  skeletonLoaderBackground: colors.outerSpace,
  brandColorSecondaryLogo: colors.darkCharcoal,
  colorSecondary200: colors.quickSilver,
  colorSecondary600: colors.white,
  foregroundInteractiveTitularDefault: colors.white,
  actionCTAToastDefault: colors.americanGreen,
  actionCTAToastError: colors.melon,
  reelBackground: colors.black,
  nPlusFocusModalBackground: colors.oldLace30Alpha,
  adaptiveText: colors.white,
  bottomTabColor1: colors.transparentCharcoalGray,
  bottomTabColor2: colors.charcoalGray,
  textHeadingChipInactive: colors.silverSand,
  widgetBackground: colors.outerSpace,
  dividerAdaptive: colors.white,
  adsBackground: colors.whiteEcho,
  chipBackground: colors.white,
  buttonFilledSecondaryOutline: colors.white,
  highlightTextPrimary: colors.coralRed,
  adaptiveDangerSecondary: colors.quickSilver,
  textAccentSecondary: colors.ultraMarineBlue,
  ctaAccentAdaptive: colors.melon,
  modalBackground: colors.black60Alpha,
  accentSecondaryPressed: colors.quickSilver
};
