export const screenNames = {
  LOGIN: 'Login' as const,
  MAIN_TAB_NAVIGATOR: 'MainTabNavigator' as const,
  HOME: 'Home' as const,
  SOCIAL_AUTH: 'SocialAuth' as const,
  STORY_PAGE_RENDERER: 'StoryPage' as const,
  SET_RECOMMENDATIONS: 'SetRecommendations' as const,
  FORGOT_PASSWORD: 'ForgotPassword' as const,
  UPDATE_PROFILE: 'UpdateProfile' as const,
  RECOMMENDED_FOR_YOU: 'RecommendedForYou' as const,
  CREATE_ACCOUNT_PASSWORD: 'CreateAccountPassword',
  SPLASH: 'Splash' as const,
  SIGN_UP_OTP: 'SignUpOtp' as const,
  NOTIFICATION_ALERT: 'NotificationAlert' as const,
  SIGN_UP_OTP_SUCCESS: 'SignUpOtpSuccess' as const,
  CREATE_NEW_PASSWORD: 'CreateNewPassword' as const,
  CREATE_NEW_PASSWORD_SUCCESS: 'CreateNewPasswordSuccess' as const,
  MY_ACCOUNT: 'MyAccount' as const,
  CONTACT_US: 'ContactUs' as const,
  SETTINGS: 'Settings' as const,
  CHANGE_PASSWORD: 'ChangePassword',
  NOTIFICATION_SETTING: 'NotificationSetting' as const,
  NOTIFICATION_DETAIL: 'NotificationDetail' as const,
  NEWSLETTERS: 'Newsletters' as const,
  DELETE_ACCOUNT_CONFIRMATION: 'DeleteAccountConfirmation' as const,
  DELETE_ACCOUNT_OTP: 'DeleteAccountOtp' as const,
  DELETE_ACCOUNT_OTP_SUCCESS: 'DeleteAccountOtpSuccess' as const,
  FORGOT_PASSWORD_OTP: 'ForgotPasswordOtp' as const,
  FORGOT_PASSWORD_OTP_VERIFY: 'ForgotPasswordOtpVerify' as const,
  AUTHOR_DETAILS: 'AuthorDetails' as const,
  ACTIVE_LIVE_BLOG_LISTING: 'ActiveLiveBlogListing' as const,
  LIVE_BLOG: 'LiveBlog' as const,
  INACTIVE_LIVE_BLOG_LISTING: 'InactiveLiveBlogListing' as const,
  VIDEOS: 'Videos' as const,
  OPINION: 'Opinión' as const,
  TALENT_LISTING: 'TalentListing' as const,
  PROGRAMS: 'Programs' as const,
  EPISODE_DETAIL_PAGE: 'EpisodeDetailPage' as const,
  ALL_EPISODES: 'AllEpisodes' as const,
  AUTHOR_BIO: 'AuthorBio' as const,
  VIDEO_DETAIL_PAGE: 'VideoDetailPage' as const,
  SHORT_INVESTIGATIONS: 'ShortInvestigations' as const,
  INTERACTIVE_LISTING: 'InteractiveListing' as const,
  NPLUS_FOCUS_LANDING_PAGE: 'NPlusFocusLandingPage' as const,
  POR_EL_PLANETA_LANDING_PAGE: 'PorElPlanetaLandingPage' as const,
  POR_EL_PLANETA_DETAIL_PAGE: 'PorElPlanetaDetailPage' as const,
  POR_EL_PLANETA_DOCUMENTARIES: 'PorElPlanetaDocumentaries' as const,
  INVESTIGATION_LISTING_SCREEN: 'InvestigationListingScreen' as const,
  INVESTIGATION_DETAIL_SCREEN: 'InvestigationDetailScreen' as const,
  SHORT_INVESTIGATION_DETAIL_SCREEN: 'ShortInvestigationDetailScreen' as const,
  LIVE_TV: 'LiveTv' as const,
  SEARCH_LANDING_PAGE: 'SearchLandingPage' as const,
  CATEGORY_LISTING: 'CategoryListing' as const,
  CATEGORY_DETAIL_SCREEN: 'CategoryTopicDetailScreen' as const,
  SEARCH_SCREEN: 'SearchScreen' as const,
  MY_NOTIFICATION: 'MyNotification' as const,
  OPINION_LANDING_PAGE: 'OpinionLandingPage' as const,
  BOOKMARKS: 'Bookmarks' as const,
  OPINION_DETAIL_PAGE: 'OpinionDetailPage' as const,
  PRESS_ROOM_LANDING: 'PressRoomLanding' as const,
  PRESS_ROOM_DETAIL: 'PressRoomDetail' as const,
  STATES_LANDING: 'StatesLanding' as const,
  STATE_DETAIL: 'StateDetail' as const,
  DUMMY_HOME: 'DummyHome' as const,
  SUBSCRIBE_TO_NEWSLETTER: 'SubscribeToNewsletter' as const,
  PRODUCTION_PAGE: 'ProductionPage' as const
} as const;

export const routeNames = {
  HOME_STACK: 'HomeStack' as const,
  AUTH_STACK: 'AuthStack' as const,
  MY_ACCOUNT_STACK: 'MyAccountStack' as const,
  VIDEOS_STACK: 'VideosStack' as const,
  OPINION_STACK: 'OpinionStack' as const
};
